apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-status
  namespace: ingress-nginx
spec:
  ports:
  - name: status
    port: 8443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-status
  namespace: ingress-nginx
spec:
  rules:
  - host: ingress-status.prateslabs.com.br
    http:
      paths:
      - path: /nginx_status
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller-admission
            port:
              number: 443