- name: install rke2
  args:
    warn: false
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION='{{ lookup('env', 'RKE2_VERSION') }}' sh -
  register: command_output
- debug:
    var: command_output.stdout_lines

- name: Enable rke2-server
  systemd:
    name: rke2-server
    enabled: true

- name: Start rke2-server
  systemd:
    name: rke2-server
    state: started

- name: Sleeping 120s
  shell: |
    sleep 120
