apiVersion: apps/v1                                                                                                                                                                                                                                                             
kind: Deployment                                                                                                                                                                                                                                                                
metadata:                                                                                                                                                                                                                                                                       
  labels:                                                                                                                                                                                                                                                                       
    app: example                                                                                                                                                                                                                                                                  
  name: example                                                                                                                                                                                                                                                                   
  namespace: default                                                                                                                                                                                                                                                            
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: quay.io/brancz/prometheus-example-app:v0.3.0
        name: example
        ports:
        - containerPort: 8080
          name: example
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example
  sessionAffinity: None
  type: ClusterIP