apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test
        image: leonardoalvesprates/web-first:v0.1
---
apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  selector:
    app: test2
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test2
spec:
  rules:
  - host: test2.prateslabs.com.br
    http:
      paths:
      - backend:
          serviceName: test2
          servicePort: 8080
        pathType: ImplementationSpecific