- name: install rke2
  args:
    warn: false
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION='{{ lookup('env', 'RKE2_VERSION') }}' sh -

- name: Enable rke2-server
  systemd:
    name: rke2-server
    enabled: true

- name: Start rke2-server
  systemd:
    name: rke2-server
    state: started
